#  ==============================================================================
#  Created by Fehmi Demiralp(Fedem) on 2025-06-09 GMT
#  Copyright (C) 2023-2025 Fedem (Fehmi Demiralp) <f.demiralp@gmail.com>
#
#  This file is generated by UMTSM using the code generator `CppGen`
#
#  Released under the MIT License
#  ==============================================================================
#

#
# KeyPressEventGenerator
#
#set(LIBKeyPressEventGenerator_SOURCE_EXTRA )
#set(LIBKeyPressEventGenerator_HEADER_EXTRA )
#set(LIBKeyPressEventGenerator_LIB_EXTRA )
#set(LIBKeyPressEventGenerator_INCLUDES_EXTRA "${CMAKE_CURRRENT_SOURCE_DIR}")
set(TESTKeyPressEventGenerator_LIB_EXTRA LIBRKeyPress_Static -lncurses)

#
# KeyPress
#
#set(LIBKeyPress_SOURCE_EXTRA )
#set(LIBKeyPress_HEADER_EXTRA )
#set(LIBKeyPress_LIB_EXTRA )
#set(LIBKeyPress_INCLUDES_EXTRA "${CMAKE_CURRRENT_SOURCE_DIR}")
set(TESTKeyPress_LIB_EXTRA -lncurses)
