#
#  ==============================================================================
#  Created by Fehmi Demiralp(Fedem) on 2025-05-29 GMT
#  Copyright (C) 2023-2025 Fedem (Fehmi Demiralp) <f.demiralp@gmail.com>
#
#  This file is generated by UMTSM using the code generator `CGen`
#
#  Released under the MIT License
#  ============================================================================
#

#
# Door
#
#set(LIBDoor_SOURCE_EXTRA )
#set(LIBDoor_HEADER_EXTRA )
set(LIBDoor_LIB_EXTRA -lncurses)
set(LIBDoor_INCLUDES_EXTRA
    ${CMAKE_SOURCE_DIR}/generated/src/engine
)
set(TESTDoor_LIB_EXTRA -lncurses)
