#
#  ==============================================================================
#  Created by Fehmi Demiralp(Fedem) on 2025-05-29 GMT
#  Copyright (C) 2023-2025 Fedem (Fehmi Demiralp) <f.demiralp@gmail.com>
#
#  This file is generated by UMTSM using the code generator `CGen`
#
#  Released under the MIT License
#  ============================================================================
#

#
# SensorCEnd
#
#set(LIBSensor_Close_End_SOURCE_EXTRA )
#set(LIBSensor_Close_End_HEADER_EXTRA )
set(LIBSensor_Close_End_LIB_EXTRA -lncurses)
set(LIBSensor_Close_End_INCLUDES_EXTRA
    ${CMAKE_SOURCE_DIR}/generated/src/door
)
set(TESTSensor_Close_End_LIB_EXTRA -lncurses)
